# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Gdr-Front-Tst

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Gdr-Front-Tst'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_94380dedcf6148819ef689b0148ba490 }}
          package: .

      - name: 'Set environment variables'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Update app settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'Gdr-Front-Tst'
          slot-name: 'production'
          app-settings-json: |
            {
              "production": true,
              "baseUrl": "https://gdrback.azurewebsites.net/",
              "key": "6>tJX#i-Bk~1@KarmaxBB",
              "domain": "provinciamicrocreditos.com",
              "clientId": "RElkef9tUvCrDq4WEIaaQPIB9YcsJd2L",
              "clientSecret": "ATOAAqTDaEdPgGgDSgBqx4fpGOu6uwGvJmEmemuNLQQN_JyRPayas4gc7dikdoMizUxUFEAE77A3",
              "baseUrlJiraAuth": "https://auth.atlassian.com/",
              "googleClientId": "396526287838-5n5ov667nqnc1i73bcnhsq03u6t3nsgj.apps.googleusercontent.com",
              "credits": "jluduena@provinciamicrocreditos.com",
              "tecnologia": [
                "mmillan@provinciamicrocreditos.com",
                "jluduena@provinciamicrocreditos.com",
                "amoragues@provinciamicrocreditos.com",
                "mbarreto@provinciamicrocreditos.com",
                "aescubilla@provinciamicrocreditos.com",
                "mmoralez@provinciamicrocreditos.com",
                "jcanepa@provinciamicrocreditos.com",
                "jpspagnuolo@provinciamicrocreditos.com",
                "echura@provinciamicrocreditos.com",
                "nrivanera@provinciamicrocreditos.com"
              ],
              "procesos": [
                "emendoza@provinciamicrocreditos.com",
                "crojas@provinciamicrocreditos.com",
                "nsuarez@provinciamicrocreditos.com"
              ],
              "soporte": [
                "saltilio@provinciamicrocreditos.com",
                "ldominguez@provinciamicrocreditos.com",
                "mlopez@provinciamicrocreditos.com",
                "gorellana@provinciamicrocreditos.com",
                "atardito@provinciamicrocreditos.com",
                "rtoledo@provinciamicrocreditos.com"
              ]
            }
